@api = http://localhost:3000/articulos

### Consultar todos los articulos
GET {{api}}

### Insertar articulos
POST {{api}}
Content-Type: application/json

{
    "Nombre": "Orlando Apodaca",
    "Correo": "orlando@gmail.com",
    "Password": "webo123",
    "TipoUsuario": "lector"
  }


### Consulta articulos por ID
GET {{api}}/1


### Eliminar articulos por Nombre
DELETE {{api}}/1


### Actualizar usuario
PUT {{api}}/1
Content-Type: application/json

{
   "Nombre": "Orlando Apodaca",
    "Correo": "orlando@gmail.com",
    "Password": "webo123",
    "TipoUsuario": "lector"
  }