@api = http://localhost:3000/users

### Consultar todos los usuarios
GET {{api}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoicGVwZTEiLCJyb2xlX2lkIjoxLCJpYXQiOjE3Mjc4MzM1MTIsImV4cCI6MTcyNzgzNzExMn0.nZTUjNCrKvOv-YoXvLHxr-Us_eROKCQKskZP9cg1Q0c

### Insertar usuarios
POST {{api}}
Content-Type: application/json


{
   "Username": "pepe1",
    "Email": "pepe1@gmail.com",
    "Password": "webo123",
    "First_name": "Orlando",
    "Last_name": "Apodaca",
    "Profile_img_path": "/images/profiles/orlando.jpg"
  }


### Consulta usuarios por ID
GET {{api}}/15


### Eliminar usuarios por Nombre
DELETE {{api}}/2


### Actualizar usuario
PUT {{api}}/9
Content-Type: application/json

{
   "Username": "DXASDSA",
    "Email": "ADS@gmail.com",
    "First_name": "Orlando",
    "Last_name": "Apodaca",
    "Profile_img_path": "/images/profiles/orlando.jpg"
  }