@api = http://localhost:3000/usuarios

### Consultar todos los usuarios
GET {{api}}

### Insertar usuarios
POST {{api}}
Content-Type: application/json

{
    "Nombre": "Orlando Apodaca",
    "Correo": "orlando@gmail.com",
    "Password": "webo123",
    "TipoUsuario": "lector"
  }


### Consulta usuarios por ID
GET {{api}}/1


### Eliminar usuarios por Nombre
DELETE {{api}}/1


### Actualizar usuario
PUT {{api}}/1
Content-Type: application/json

{
   "Nombre": "Orlando Apodaca",
    "Correo": "orlando@gmail.com",
    "Password": "webo123",
    "TipoUsuario": "lector"
  }